Repository Project-Nu11/t-issue, pull requests merged in 2025-09, with the labels that each got.

#6 [feature] 관리자 공지사항 추가 기능 구현
  src/main/java/com/toiletissue/config/MybatisConfig.java
  src/main/java/com/toiletissue/notice/controller/NoticeController.java
  src/main/java/com/toiletissue/notice/model/dao/NoticeMapper.java
  src/main/java/com/toiletissue/notice/model/dto/NoticeDTO.java
  src/main/java/com/toiletissue/notice/model/service/NoticeService.java
  src/main/resources/mappers/NoticeMapper.xml
  src/main/resources/templates/error/error.html
  src/main/resources/templates/mypage/mypage.html
  src/main/resources/templates/notice/delete.html
  src/main/resources/templates/notice/insert.html
  src/main/resources/templates/notice/manager.html
  src/main/resources/templates/request/request.html
  src/main/resources/templates/review/review.html
Labels: feature

#7 [feature] 회원가입 페이지 구현
  src/main/java/com/toiletissue/common/MemberRole.java
  src/main/java/com/toiletissue/member/model/dao/MemberMapper.java
  src/main/resources/mappers/MemberMapper.xml
Labels: feature

#20 [feature] 사용자 화장실 전체 목록 조회 구현
  .gitignore
  src/main/java/com/toiletissue/member/model/dto/MemberSignupDTO.java
  src/main/java/com/toiletissue/notice/controller/NoticeController.java
  src/main/java/com/toiletissue/timer/controller/TimerController.java
  src/main/java/com/toiletissue/toilet/controller/ToiletController.java
  src/main/java/com/toiletissue/toilet/model/dao/ToiletMapper.java
  src/main/java/com/toiletissue/toilet/model/dto/ToiletDTO.java
  src/main/java/com/toiletissue/toilet/model/service/ToiletService.java
  src/main/resources/templates/main.html
  src/main/resources/templates/timer.html
  src/main/resources/templates/toilet/subway.html
  src/main/resources/templates/toilet/subwayName.html
  src/main/resources/templates/toilet/toiletName.html
  src/main/resources/toiletApi.http
Labels: feature

#22 [feature] 타이머 기능 구현
  src/main/resources/templates/timer.html
Labels: feature

#52 [feature] 관리자 문의 페이지 구현
  src/main/java/com/toiletissue/notice/controller/NoticeController.java
  src/main/java/com/toiletissue/request/controller/RequestController.java
  src/main/java/com/toiletissue/request/model/dao/RequestMapper.java
  src/main/java/com/toiletissue/request/model/dto/RequestDTO.java
  src/main/java/com/toiletissue/request/model/service/RequestService.java
  src/main/resources/mappers/RequestMapper.xml
  src/main/resources/templates/manager/main.html
  src/main/resources/templates/request/manager.html
Labels: feature

#59 [feature] 회원 가입 페이지 - 개인정보 입력(아이디 중복 확인, 비밀번호 일치) 기능 구현
  src/main/java/com/toiletissue/config/SecurityConfig.java
  src/main/java/com/toiletissue/member/controller/MemberController.java
  src/main/java/com/toiletissue/member/model/dao/MemberMapper.java
  src/main/java/com/toiletissue/member/model/service/MemberService.java
  src/main/java/com/toiletissue/mypage/controller/MyPageController.java
  src/main/java/com/toiletissue/mypage/model/service/MyPageService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/common/header.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/register.html
  src/main/resources/templates/member/select.html
  src/main/resources/templates/mypage/mypage.html
Labels: feature

#63 [feature] 화장실 상세 조회 api 연동
  src/main/java/com/toiletissue/auth/controller/MainController.java
  src/main/java/com/toiletissue/toilet/controller/ToiletController.java
  src/main/java/com/toiletissue/toilet/model/dto/ToiletDTO.java
  src/main/resources/static/icon/baby.png
  src/main/resources/static/icon/diffable.png
  src/main/resources/static/icon/free-icon-pause-button-64485.png
  src/main/resources/static/icon/free-icon-play-4211344.png
  src/main/resources/static/icon/free-icon-stop-button-7513168.png
  src/main/resources/static/icon/pen.png
  src/main/resources/static/icon/toilet.png
  src/main/resources/static/icon/women.png
  src/main/resources/static/image/512-1.png
  src/main/resources/templates/common/header.html
  src/main/resources/templates/main.html
  src/main/resources/templates/timer.html
  src/main/resources/templates/toilet/details.html
  src/main/resources/templates/toilet/stationList.html
Labels: feature

#65 [feature] 사용자 아이디 찾기, 비밀번호 찾기 구현
  src/main/java/com/toiletissue/config/SecurityConfig.java
  src/main/java/com/toiletissue/member/controller/MemberController.java
  src/main/java/com/toiletissue/member/model/dao/MemberMapper.java
  src/main/java/com/toiletissue/member/model/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/member/find.html
  src/main/resources/templates/member/login.html
Labels: feature

#73 [feature] 마이페이지 구현
  gradlew
  src/main/java/com/toiletissue/config/SecurityConfig.java
  src/main/java/com/toiletissue/member/controller/MemberController.java
  src/main/java/com/toiletissue/mypage/controller/MyPageController.java
  src/main/java/com/toiletissue/mypage/model/dao/MyPageMapper.java
  src/main/java/com/toiletissue/mypage/model/service/MyPageService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/MypageMapper.xml
  src/main/resources/templates/member/find.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/register.html
  src/main/resources/templates/mypage/mypage.html
Labels: feature

#77 [feature] 관리자 페이지 신고 리뷰, 선택 리뷰 관리 페이지 구현
  src/main/java/com/toiletissue/request/controller/RequestController.java
  src/main/java/com/toiletissue/review/controller/ReviewController.java
  src/main/java/com/toiletissue/review/model/dao/ReviewMapper.java
  src/main/java/com/toiletissue/review/model/dto/ReviewDTO.java
  src/main/java/com/toiletissue/review/model/service/ReviewService.java
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/templates/notice/manager.html
  src/main/resources/templates/request/manager.html
  src/main/resources/templates/review/declared.html
  src/main/resources/templates/review/search.html
  src/main/resources/templates/toilet/details.html
Labels: feature

#79 [fix] 관리자 신고 리뷰 관리 페이지 벌점 부과 기능 추가
  src/main/java/com/toiletissue/auth/controller/MainController.java
  src/main/java/com/toiletissue/member/model/dto/MemberDTO.java
  src/main/java/com/toiletissue/request/controller/RequestController.java
  src/main/java/com/toiletissue/review/controller/ReviewController.java
  src/main/java/com/toiletissue/review/model/dao/ReviewMapper.java
  src/main/java/com/toiletissue/review/model/dto/ReviewDTO.java
  src/main/java/com/toiletissue/review/model/service/ReviewService.java
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/templates/request/manager.html
  src/main/resources/templates/review/declared.html
Labels: fix

#100 [fix] 관리자 페이지 crud 유효성 검사 기능 추가 #96
  src/main/java/com/toiletissue/member/controller/MemberController.java
  src/main/java/com/toiletissue/member/model/dao/MemberMapper.java
  src/main/java/com/toiletissue/member/model/service/MemberService.java
  src/main/java/com/toiletissue/notice/controller/NoticeController.java
  src/main/java/com/toiletissue/notice/model/dao/NoticeMapper.java
  src/main/java/com/toiletissue/notice/model/service/NoticeService.java
  src/main/java/com/toiletissue/request/controller/RequestController.java
  src/main/java/com/toiletissue/request/model/dao/RequestMapper.java
  src/main/java/com/toiletissue/request/model/service/RequestService.java
  src/main/java/com/toiletissue/review/controller/ReviewController.java
  src/main/java/com/toiletissue/review/model/dao/ReviewMapper.java
  src/main/java/com/toiletissue/review/model/service/ReviewService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/NoticeMapper.xml
  src/main/resources/mappers/RequestMapper.xml
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/templates/member/manager.html
  src/main/resources/templates/notice/manager.html
  src/main/resources/templates/request/manager.html
  src/main/resources/templates/request/member.html
  src/main/resources/templates/review/declared.html
  src/main/resources/templates/review/search.html
Labels: feature, fix

#102 [feature] 사용자 마이페이지 내 리뷰 조회
  src/main/resources/templates/mypage/review.html
Labels: feature

#110 [feature] 리뷰 신고 기능 추가
  src/main/java/com/toiletissue/declaration/model/dao/DeclarationMapper.java
  src/main/java/com/toiletissue/declaration/model/dto/DeclarationDTO.java
  src/main/java/com/toiletissue/declaration/model/service/DeclarationService.java
  src/main/java/com/toiletissue/penalty/controller/PenaltyController.java
  src/main/java/com/toiletissue/review/controller/ReviewController.java
  src/main/java/com/toiletissue/review/model/dao/ReviewMapper.java
  src/main/java/com/toiletissue/review/model/service/ReviewService.java
  src/main/java/com/toiletissue/toilet/controller/ToiletController.java
  src/main/resources/mappers/DeclarationMapper.xml
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/templates/penalty/manager.html
  src/main/resources/templates/toilet/details.html
Labels: feature

#113 [fix] 화장실 검색 수정
  .gitignore
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage/mypage.html
  src/main/resources/templates/notice/user.html
Labels: fix

#115 [fix] 리뷰 조회 오류 수정
  src/main/java/com/toiletissue/review/model/dao/ReviewMapper.java
  src/main/java/com/toiletissue/review/model/service/ReviewService.java
  src/main/java/com/toiletissue/toilet/controller/ToiletController.java
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/templates/toilet/details.html
  src/main/resources/templates/toilet/station.html
Labels: fix

#116 [feature] 화장실 상세 페이지 리뷰 조회 시 별점 처리
  src/main/resources/templates/toilet/details.html
Labels: feature, fix
